delete from public.projects
where title in ('CASSIA', 'CASSIA CORAL GABLES', 'CASSIA CORAL GABLES RESIDENCES');

insert into public.projects (
  title,
  badge_es,
  badge_en,
  location_es,
  location_en,
  residences_es,
  residences_en,
  baths_es,
  baths_en,
  type_es,
  type_en,
  delivery_es,
  delivery_en,
  ideal_for_es,
  ideal_for_en,
  parking_es,
  parking_en,
  hook_es,
  hook_en,
  filter_location_es,
  filter_location_en,
  filter_type_es,
  filter_type_en,
  filter_strategy_es,
  filter_strategy_en,
  image_url,
  image_path,
  price_from,
  sort_order,
  is_published,
  is_featured
)
values (
  'CASSIA CORAL GABLES',
  'Lujo turn-key',
  'Turn-key luxury',
  'Merrick Park District, Coral Gables',
  'Merrick Park District, Coral Gables',
  '1, 2 y 3 habitaciones amuebladas',
  '1, 2 and 3 furnished bedrooms',
  '—',
  '—',
  'Airbnb / Vrbo permitido',
  'Airbnb / Vrbo allowed',
  '2027',
  '2027',
  'Inversionistas que buscan una propiedad turn-key en una de las zonas más estables y exclusivas de Miami, con renta corta permitida, seguridad patrimonial y valorización a largo plazo.',
  'Investors seeking a turn-key property in one of Miami''s most stable and exclusive areas, with short-term rentals allowed, wealth preservation, and long-term appreciation.',
  null,
  null,
  'Residencias turn-key amuebladas por RH, a pasos de Merrick Park, con renta corta permitida desde el día 1.',
  'Turn-key residences furnished by RH, steps from Merrick Park, with short-term rentals allowed from day one.',
  'Coral Gables, Miami',
  'Coral Gables, Miami',
  'Airbnb / Vrbo permitido',
  'Airbnb / Vrbo allowed',
  'Renta corta en ubicación premium de Coral Gables',
  'Short-term rental in a premium Coral Gables location',
  'https://velgoadpmhssqptkcjam.supabase.co/storage/v1/object/public/project-images/projects/cassia/hero.webp',
  'projects/cassia/hero.webp',
  773000,
  60,
  true,
  false
);
