delete from public.projects
where title in ('MIDTOWN PARK', 'HOUSE OF WELLNESS');

insert into public.projects (
  title,
  badge_es,
  badge_en,
  location_es,
  location_en,
  residences_es,
  residences_en,
  baths_es,
  baths_en,
  type_es,
  type_en,
  delivery_es,
  delivery_en,
  ideal_for_es,
  ideal_for_en,
  parking_es,
  parking_en,
  hook_es,
  hook_en,
  filter_location_es,
  filter_location_en,
  filter_type_es,
  filter_type_en,
  filter_strategy_es,
  filter_strategy_en,
  image_url,
  image_path,
  price_from,
  sort_order,
  is_published,
  is_featured
)
values (
  'HOUSE OF WELLNESS',
  'Bienestar residencial',
  'Wellness residences',
  'Brickell, Miami',
  'Brickell, Miami',
  'Studios - 2 habitaciones',
  'Studios - 2 bedrooms',
  '—',
  '—',
  'Mínimo 30 días',
  '30-day minimum',
  '2028',
  '2028',
  'Atraer inquilinos de calidad y generar ingresos estables a largo plazo.',
  'Attract quality tenants and generate stable long-term income.',
  null,
  null,
  'Un estilo de vida diseñado para el bienestar, dentro y fuera de casa.',
  'A lifestyle designed for wellness, inside and outside the home.',
  'Brickell, Miami',
  'Brickell, Miami',
  'Mínimo 30 días',
  '30-day minimum',
  'Enfoque residencial con ingresos estables a largo plazo',
  'Residential focus with stable long-term income',
  'https://velgoadpmhssqptkcjam.supabase.co/storage/v1/object/public/project-images/projects/house-of-wellness/building-hero-closeup.webp',
  'projects/house-of-wellness/building-hero-closeup.webp',
  400000,
  50,
  true,
  false
);
