delete from public.projects
where title in ('REUNION VILLAGE', 'STOREY LAKE', 'WINDSOR CAY', 'EVERBE');

insert into public.projects (
  title,
  badge_es,
  badge_en,
  location_es,
  location_en,
  residences_es,
  residences_en,
  baths_es,
  baths_en,
  type_es,
  type_en,
  delivery_es,
  delivery_en,
  ideal_for_es,
  ideal_for_en,
  parking_es,
  parking_en,
  hook_es,
  hook_en,
  filter_location_es,
  filter_location_en,
  filter_type_es,
  filter_type_en,
  filter_strategy_es,
  filter_strategy_en,
  image_url,
  image_path,
  gallery_images,
  price_from,
  city,
  sort_order,
  is_published,
  is_featured
)
values
(
  'REUNION VILLAGE',
  'Comunidad vacacional',
  'Vacation community',
  'Reunion / Kissimmee',
  'Reunion / Kissimmee',
  'Casas / townhomes',
  'Homes / townhomes',
  '—',
  '—',
  'Short-term rental',
  'Short-term rental',
  '20XX',
  '20XX',
  'Para inversionistas que buscan exposición al mercado turístico de Orlando y una experiencia tipo resort.',
  'For investors seeking Orlando tourism exposure and a resort-style experience.',
  null,
  null,
  'Comunidad orientada a renta vacacional con posibilidad de administración profesional.',
  'Vacation-rental community with potential for professional management.',
  'Reunion / Kissimmee',
  'Reunion / Kissimmee',
  'Short-term rental',
  'Short-term rental',
  'Mercado turístico de Orlando con experiencia tipo resort',
  'Orlando tourism market with a resort-style experience',
  '',
  null,
  '[]'::jsonb,
  null,
  'orlando',
  70,
  true,
  true
),
(
  'STOREY LAKE',
  'Cercanía a parques',
  'Near theme parks',
  'Kissimmee',
  'Kissimmee',
  'Townhomes / casas',
  'Townhomes / homes',
  '—',
  '—',
  'Renta vacacional',
  'Vacation rental',
  '20XX',
  '20XX',
  'Fácil de explicar a compradores internacionales por ubicación, uso y experiencia.',
  'Easy to explain to international buyers thanks to location, use case, and experience.',
  null,
  null,
  'Alta demanda por cercanía a parques temáticos y perfil familiar/turístico.',
  'High demand due to proximity to theme parks and a family/tourism profile.',
  'Kissimmee',
  'Kissimmee',
  'Renta vacacional',
  'Vacation rental',
  'Cercanía a parques temáticos y demanda familiar/turística',
  'Proximity to theme parks and family/tourism demand',
  '',
  null,
  '[]'::jsonb,
  null,
  'orlando',
  80,
  true,
  false
),
(
  'WINDSOR CAY',
  'Resort rental',
  'Resort rental',
  'Área Orlando',
  'Orlando area',
  'Casas familiares',
  'Family homes',
  '—',
  '—',
  'Renta corta',
  'Short-term rental',
  '20XX',
  '20XX',
  'La tesis se apoya en amenities, escala de comunidad y demanda turística recurrente.',
  'The thesis is supported by amenities, community scale, and recurring tourism demand.',
  null,
  null,
  'Perfil resort para inversionista que busca amenities fuertes y experiencia vacacional completa.',
  'Resort profile for investors seeking strong amenities and a complete vacation experience.',
  'Área Orlando',
  'Orlando area',
  'Renta corta',
  'Short-term rental',
  'Amenities fuertes y demanda turística recurrente',
  'Strong amenities and recurring tourism demand',
  '',
  null,
  '[]'::jsonb,
  null,
  'orlando',
  90,
  true,
  false
),
(
  'EVERBE',
  'Alternativa local',
  'Local alternative',
  'Orlando',
  'Orlando',
  'Casas modernas',
  'Modern homes',
  '—',
  '—',
  'Vivienda / largo plazo',
  'Primary home / long-term',
  '20XX',
  '20XX',
  'Ayuda a cubrir el perfil residente o comprador con estrategia más estable.',
  'Helps cover the resident buyer or a buyer with a more stable strategy.',
  null,
  null,
  'Alternativa para comprador local o inversión de largo plazo, no necesariamente vacacional.',
  'Alternative for local buyers or long-term investment, not necessarily vacation-focused.',
  'Orlando',
  'Orlando',
  'Vivienda / largo plazo',
  'Primary home / long-term',
  'Perfil residente o comprador con estrategia estable',
  'Resident buyer or stable strategy profile',
  '',
  null,
  '[]'::jsonb,
  null,
  'orlando',
  100,
  true,
  false
);
