delete from public.projects;

insert into public.projects (
  title,
  badge_es,
  badge_en,
  location_es,
  location_en,
  residences_es,
  residences_en,
  baths_es,
  baths_en,
  type_es,
  type_en,
  delivery_es,
  delivery_en,
  ideal_for_es,
  ideal_for_en,
  parking_es,
  parking_en,
  hook_es,
  hook_en,
  filter_location_es,
  filter_location_en,
  filter_type_es,
  filter_type_en,
  filter_strategy_es,
  filter_strategy_en,
  image_url,
  image_path,
  price_from,
  sort_order,
  is_published,
  is_featured
)
values (
  'EDGE HOUSE',
  'Inversión',
  'Investment',
  'Edgewater, Miami',
  'Edgewater, Miami',
  'Studios - 3 habitaciones',
  'Studios - 3 bedrooms',
  'Desde 1 baño',
  'From 1 bathroom',
  'Airbnb permitido',
  'Airbnb allowed',
  '2030',
  '2030',
  'Inversionistas en renta corta',
  'Short-term rental investors',
  null,
  null,
  'Invierte en Airbnb en el corazón de Edgewater, una de las zonas con mayor crecimiento y demanda.',
  'Invest in Airbnb in the heart of Edgewater, one of Miami''s highest-growth, high-demand areas.',
  'Edgewater, Miami',
  'Edgewater, Miami',
  'Airbnb permitido',
  'Airbnb allowed',
  'Renta corta',
  'Short-term rental',
  'https://velgoadpmhssqptkcjam.supabase.co/storage/v1/object/public/project-images/projects/edge-house-hero.webp',
  'projects/edge-house-hero.webp',
  540000,
  10,
  true,
  true
);
