delete from public.projects
where title in (
  'BLOOM',
  'EDGE HOUSE',
  'EDITION RESIDENCES',
  'CASSIA',
  'THE WILLIAM',
  'MIDTOWN PARK',
  'FRIDA KAHLO RESIDENCES',
  'DELANO RESIDENCES',
  'MANDARIN ORIENTAL RESIDENCES',
  '3000 WATERSIDE',
  'REUNION VILLAGE',
  'CELEBRATION',
  'WINTER GARDEN',
  'CLERMONT'
);

insert into public.projects (
  title,
  badge_es,
  badge_en,
  location_es,
  location_en,
  residences_es,
  residences_en,
  baths_es,
  baths_en,
  type_es,
  type_en,
  delivery_es,
  delivery_en,
  ideal_for_es,
  ideal_for_en,
  parking_es,
  parking_en,
  hook_es,
  hook_en,
  filter_location_es,
  filter_location_en,
  filter_type_es,
  filter_type_en,
  filter_strategy_es,
  filter_strategy_en,
  image_url,
  image_path,
  sort_order,
  is_published
)
values
  (
    'BLOOM',
    'Preconstrucción',
    'Pre-construction',
    'North Miami / SoLeMia',
    'North Miami / SoLeMia',
    '2 habitaciones + den',
    '2 bedrooms + den',
    '2.5 baños',
    '2.5 bathrooms',
    'Boutique building',
    'Boutique building',
    '2028',
    '2028',
    'Inversión renta 90 días',
    '90-day rental investment',
    'Asignado',
    'Assigned',
    'Diseño funcional con medio baño adicional ideal para inversión.',
    'Functional layouts with an additional half bath designed for investors.',
    'North Miami / SoLeMia',
    'North Miami / SoLeMia',
    'Boutique',
    'Boutique',
    'Renta 90 días',
    '90-day rental',
    'https://velgoadpmhssqptkcjam.supabase.co/storage/v1/object/public/project-images/projects/bloom.webp',
    'projects/bloom.webp',
    10,
    true
  ),
  (
    'EDGE HOUSE',
    'Inversión',
    'Investment',
    'Edgewater Miami',
    'Edgewater Miami',
    'Estudios a 2 habitaciones',
    'Studios to 2 bedrooms',
    'Desde 1 baño',
    'From 1 bathroom',
    'Condo residencias inversión',
    'Investment condo residences',
    '2030',
    '2030',
    'Rentas cortas y largas',
    'Short- and long-term rentals',
    null,
    null,
    'Alta flexibilidad de renta en una de las zonas con mayor crecimiento de Miami.',
    'Strong rental flexibility in one of Miami''s fastest-growing neighborhoods.',
    'Edgewater Miami',
    'Edgewater Miami',
    'Condo inversión',
    'Investment condo',
    'Rentas cortas y largas',
    'Short and long rentals',
    'https://velgoadpmhssqptkcjam.supabase.co/storage/v1/object/public/project-images/projects/edge-house.jpg',
    'projects/edge-house.jpg',
    20,
    true
  ),
  (
    'EDITION RESIDENCES',
    'Waterfront',
    'Waterfront',
    'Edgewater Miami',
    'Edgewater Miami',
    '1 a 4 habitaciones',
    '1 to 4 bedrooms',
    'Desde 1.5 baños',
    'From 1.5 bathrooms',
    'Branded luxury residences',
    'Branded luxury residences',
    'Preconstrucción',
    'Pre-construction',
    'Inversión y lujo',
    'Investment and luxury',
    null,
    null,
    'Residencias de marca frente al agua con alto nivel y valorización.',
    'Waterfront branded residences with a high-end profile and strong appreciation potential.',
    'Edgewater Miami',
    'Edgewater Miami',
    'Branded luxury',
    'Branded luxury',
    'Inversión y lujo',
    'Investment and luxury',
    'https://velgoadpmhssqptkcjam.supabase.co/storage/v1/object/public/project-images/projects/edition-residences.jpg',
    'projects/edition-residences.jpg',
    30,
    true
  ),
  (
    'CASSIA',
    'Rentas cortas',
    'Short-term',
    'Coral Gables',
    'Coral Gables',
    'Estudios a 2 habitaciones',
    'Studios to 2 bedrooms',
    'Desde 1 baño',
    'From 1 bathroom',
    'Condo hotel',
    'Condo hotel',
    '2027 aprox.',
    'Approx. 2027',
    'Rentas cortas',
    'Short-term rentals',
    'Incluido',
    'Included',
    'Ubicación premium con flexibilidad de rentas cortas.',
    'Premium location with short-term rental flexibility.',
    'Coral Gables',
    'Coral Gables',
    'Condo hotel',
    'Condo hotel',
    'Rentas cortas',
    'Short-term rentals',
    'https://velgoadpmhssqptkcjam.supabase.co/storage/v1/object/public/project-images/projects/cassia.png',
    'projects/cassia.png',
    40,
    true
  ),
  (
    'THE WILLIAM',
    'Largo plazo',
    'Long-term',
    'North Miami Beach',
    'North Miami Beach',
    'Estudios a 3 habitaciones',
    'Studios to 3 bedrooms',
    'Desde 1 baño',
    'From 1 bathroom',
    'Condo residencias',
    'Condo residences',
    '2029 aprox.',
    'Approx. 2029',
    'Inversión largo plazo',
    'Long-term investment',
    null,
    null,
    'Proyecto moderno cerca de Aventura con excelente proyección.',
    'A modern project near Aventura with excellent upside.',
    'North Miami Beach',
    'North Miami Beach',
    'Condo residences',
    'Condo residences',
    'Largo plazo',
    'Long-term',
    'https://velgoadpmhssqptkcjam.supabase.co/storage/v1/object/public/project-images/projects/the-william.jpg',
    'projects/the-william.jpg',
    50,
    true
  ),
  (
    'MIDTOWN PARK',
    'Urban luxury',
    'Urban luxury',
    'Midtown Miami',
    'Midtown Miami',
    '1 a 3 habitaciones',
    '1 to 3 bedrooms',
    'Desde 1 baño',
    'From 1 bathroom',
    'Urban luxury residences',
    'Urban luxury residences',
    'En fases',
    'Phased delivery',
    'Inversión y estilo de vida',
    'Investment and lifestyle',
    null,
    null,
    'Nuevo distrito urbano en una de las zonas con mayor crecimiento.',
    'A new urban district in one of Miami''s highest-growth areas.',
    'Midtown Miami',
    'Midtown Miami',
    'Urban luxury',
    'Urban luxury',
    'Lifestyle e inversión',
    'Lifestyle and investment',
    'https://velgoadpmhssqptkcjam.supabase.co/storage/v1/object/public/project-images/projects/midtown-park.jpg',
    'projects/midtown-park.jpg',
    60,
    true
  ),
  (
    'FRIDA KAHLO RESIDENCES',
    'Boutique',
    'Boutique',
    'Miami urbano',
    'Urban Miami',
    '1 a 3 habitaciones',
    '1 to 3 bedrooms',
    'Desde 1 baño',
    'From 1 bathroom',
    'Boutique residences',
    'Boutique residences',
    'Preconstrucción',
    'Pre-construction',
    'Inversión',
    'Investment',
    null,
    null,
    'Proyecto de diseño exclusivo con alto potencial de valorización.',
    'An exclusive design-forward project with high appreciation potential.',
    'Miami urbano',
    'Urban Miami',
    'Boutique',
    'Boutique',
    'Valorización',
    'Appreciation',
    'https://velgoadpmhssqptkcjam.supabase.co/storage/v1/object/public/project-images/projects/frida-kahlo.webp',
    'projects/frida-kahlo.webp',
    70,
    true
  ),
  (
    'DELANO RESIDENCES',
    'Branded',
    'Branded',
    'Brickell',
    'Brickell',
    'Estudios a 3 habitaciones',
    'Studios to 3 bedrooms',
    'Desde 1 baño',
    'From 1 bathroom',
    'Branded residences',
    'Branded residences',
    'Preconstrucción',
    'Pre-construction',
    'Inversión y uso personal',
    'Investment and personal use',
    null,
    null,
    'Marca reconocida en una de las zonas más demandadas.',
    'A recognized brand in one of Miami''s most in-demand locations.',
    'Brickell',
    'Brickell',
    'Branded residences',
    'Branded residences',
    'Uso personal e inversión',
    'Personal use and investment',
    'https://velgoadpmhssqptkcjam.supabase.co/storage/v1/object/public/project-images/projects/delano.webp',
    'projects/delano.webp',
    80,
    true
  ),
  (
    'MANDARIN ORIENTAL RESIDENCES',
    'Luxury',
    'Luxury',
    'Brickell Key',
    'Brickell Key',
    '2 a 5 habitaciones',
    '2 to 5 bedrooms',
    'Desde 2.5 baños',
    'From 2.5 bathrooms',
    'Branded luxury residences',
    'Branded luxury residences',
    'Preconstrucción',
    'Pre-construction',
    'Inversión patrimonial',
    'Legacy investment',
    null,
    null,
    'Uno de los desarrollos más exclusivos y emblemáticos de Miami.',
    'One of Miami''s most exclusive and emblematic developments.',
    'Brickell Key',
    'Brickell Key',
    'Branded luxury',
    'Branded luxury',
    'Patrimonial',
    'Legacy',
    'https://velgoadpmhssqptkcjam.supabase.co/storage/v1/object/public/project-images/projects/mandarin-oriental.png',
    'projects/mandarin-oriental.png',
    90,
    true
  ),
  (
    '3000 WATERSIDE',
    'Waterfront',
    'Waterfront',
    'Fort Lauderdale',
    'Fort Lauderdale',
    '1 a 3 habitaciones',
    '1 to 3 bedrooms',
    'Desde 1.5 baños',
    'From 1.5 bathrooms',
    'Waterfront residences',
    'Waterfront residences',
    'En construcción',
    'Under construction',
    'Inversión y lifestyle',
    'Investment and lifestyle',
    null,
    null,
    'Residencias frente al agua con excelente proyección.',
    'Waterfront residences with strong future upside.',
    'Fort Lauderdale',
    'Fort Lauderdale',
    'Waterfront',
    'Waterfront',
    'Lifestyle e inversión',
    'Lifestyle and investment',
    'https://velgoadpmhssqptkcjam.supabase.co/storage/v1/object/public/project-images/projects/waterside-3000.jpg',
    'projects/waterside-3000.jpg',
    100,
    true
  ),
  (
    'REUNION VILLAGE',
    'Vacacional',
    'Vacation',
    'Kissimmee cerca de Disney',
    'Kissimmee near Disney',
    '3 a 5 habitaciones',
    '3 to 5 bedrooms',
    'Desde 2.5 baños',
    'From 2.5 bathrooms',
    'Single family homes',
    'Single family homes',
    'En fases',
    'Phased delivery',
    'Rentas cortas y largas',
    'Short- and long-term rentals',
    null,
    null,
    'Comunidad con alta demanda turística ideal para inversión vacacional.',
    'A high-tourism community ideal for vacation-rental investment.',
    'Kissimmee / Disney',
    'Kissimmee / Disney',
    'Single family',
    'Single family',
    'Rentas cortas y largas',
    'Short and long rentals',
    'https://velgoadpmhssqptkcjam.supabase.co/storage/v1/object/public/project-images/projects/reunion-village.jpg',
    'projects/reunion-village.jpg',
    110,
    true
  ),
  (
    'CELEBRATION',
    'Residencial',
    'Residential',
    'Celebration, Florida',
    'Celebration, Florida',
    '3 a 5 habitaciones',
    '3 to 5 bedrooms',
    'Desde 2 baños',
    'From 2 bathrooms',
    'Single family homes y townhomes',
    'Single family homes and townhomes',
    'Nueva construcción disponible',
    'New construction available',
    'Inversión y vivienda futura',
    'Investment and future homeownership',
    null,
    null,
    'Comunidad planificada con alta demanda y excelente valorización.',
    'A master-planned community with strong demand and excellent appreciation.',
    'Celebration',
    'Celebration',
    'Single family y townhomes',
    'Single family and townhomes',
    'Vivienda futura',
    'Future homeownership',
    'https://velgoadpmhssqptkcjam.supabase.co/storage/v1/object/public/project-images/projects/celebration.jpg',
    'projects/celebration.jpg',
    120,
    true
  ),
  (
    'WINTER GARDEN',
    'Crecimiento',
    'Growth',
    'Winter Garden / Horizon West',
    'Winter Garden / Horizon West',
    '3 a 5 habitaciones',
    '3 to 5 bedrooms',
    'Desde 2 baños',
    'From 2 bathrooms',
    'Single family homes',
    'Single family homes',
    'Nuevas comunidades',
    'New communities',
    'Inversión largo plazo',
    'Long-term investment',
    null,
    null,
    'Una de las zonas con mayor crecimiento y demanda residencial.',
    'One of the region''s fastest-growing residential areas.',
    'Winter Garden / Horizon West',
    'Winter Garden / Horizon West',
    'Single family',
    'Single family',
    'Largo plazo',
    'Long-term',
    'https://velgoadpmhssqptkcjam.supabase.co/storage/v1/object/public/project-images/projects/winter-garden.jpg',
    'projects/winter-garden.jpg',
    130,
    true
  ),
  (
    'CLERMONT',
    'Oportunidad',
    'Opportunity',
    'Clermont, Florida',
    'Clermont, Florida',
    '3 a 5 habitaciones',
    '3 to 5 bedrooms',
    'Desde 2 baños',
    'From 2 bathrooms',
    'Single family homes',
    'Single family homes',
    'Nuevas comunidades',
    'New communities',
    'Inversión con precios competitivos',
    'Investment with competitive pricing',
    null,
    null,
    'Zona en expansión con alto potencial de valorización.',
    'An expanding area with strong appreciation potential.',
    'Clermont',
    'Clermont',
    'Single family',
    'Single family',
    'Precios competitivos',
    'Competitive pricing',
    'https://velgoadpmhssqptkcjam.supabase.co/storage/v1/object/public/project-images/projects/clermont.jpg',
    'projects/clermont.jpg',
    140,
    true
  );
