insert into public.projects (
  title,
  badge_es,
  badge_en,
  location_es,
  location_en,
  residences_es,
  residences_en,
  baths_es,
  baths_en,
  type_es,
  type_en,
  delivery_es,
  delivery_en,
  ideal_for_es,
  ideal_for_en,
  parking_es,
  parking_en,
  hook_es,
  hook_en,
  filter_location_es,
  filter_location_en,
  filter_type_es,
  filter_type_en,
  filter_strategy_es,
  filter_strategy_en,
  image_url,
  image_path,
  price_from,
  sort_order,
  is_published,
  is_featured
)
values (
  'THE WILLIAM RESIDENCES',
  'Entrada temprana',
  'Early entry',
  'North Miami Beach',
  'North Miami Beach',
  'Studios - 3 habitaciones',
  'Studios - 3 bedrooms',
  '—',
  '—',
  'Mínimo 90 días',
  '90-day minimum',
  '2029',
  '2029',
  'The William Residences es una torre refinada de 26 pisos y 374 residencias en North Miami Beach, cerca de playas, tiendas, restaurantes, aeropuertos, centros de negocios y espacios culturales. Su ubicación conectada y renta mínima de 90 días lo posicionan como una alternativa para diversificar capital en una zona con proyección real.',
  'The William Residences is a refined 26-story tower with 374 residences in North Miami Beach, close to beaches, shopping, restaurants, airports, business centers, and cultural venues. Its connected location and 90-day minimum rental policy position it as an alternative for diversifying capital in an area with real growth potential.',
  null,
  null,
  'The William Residences: una oportunidad estratégica para entrar temprano en un mercado en expansión.',
  'The William Residences: a strategic opportunity to enter early in an expanding market.',
  'North Miami Beach',
  'North Miami Beach',
  'Mínimo 90 días',
  '90-day minimum',
  'Diversificar capital en zona con proyección real',
  'Diversify capital in an area with real growth potential',
  'https://velgoadpmhssqptkcjam.supabase.co/storage/v1/object/public/project-images/projects/the-william-hero.webp',
  'projects/the-william-hero.webp',
  380000,
  30,
  true,
  false
)
on conflict do nothing;
