insert into public.projects (
  title,
  badge_es,
  badge_en,
  location_es,
  location_en,
  residences_es,
  residences_en,
  baths_es,
  baths_en,
  type_es,
  type_en,
  delivery_es,
  delivery_en,
  ideal_for_es,
  ideal_for_en,
  parking_es,
  parking_en,
  hook_es,
  hook_en,
  filter_location_es,
  filter_location_en,
  filter_type_es,
  filter_type_en,
  filter_strategy_es,
  filter_strategy_en,
  image_url,
  image_path,
  price_from,
  sort_order,
  is_published,
  is_featured
)
values (
  'BLOOM NORTH MIAMI',
  'Inversión boutique',
  'Boutique investment',
  'North Miami',
  'North Miami',
  '2 habitaciones + den',
  '2 bedrooms + den',
  '—',
  '—',
  'Mínimo 90 días',
  '90-day minimum',
  '2029',
  '2029',
  'Proyecto boutique de 35 unidades y 9 pisos en North Miami, ubicado en una zona en plena transformación urbana con alto potencial de valorización. Su precio de entrada accesible frente a otras áreas de Miami, combinado con rentas mínimas flexibles de 90 días, lo convierte en una opción ideal para inversionistas que buscan generar ingresos y posicionarse temprano en un mercado en crecimiento.',
  'A 35-unit, 9-story boutique project in North Miami, located in an area undergoing urban transformation with strong appreciation potential. Its accessible entry price compared with other Miami areas, combined with flexible 90-day minimum rentals, makes it ideal for investors seeking income and early positioning in a growing market.',
  null,
  null,
  'Donde el crecimiento de North Miami se convierte en oportunidad para construir patrimonio.',
  'Where North Miami''s growth becomes an opportunity to build long-term wealth.',
  'North Miami',
  'North Miami',
  'Mínimo 90 días',
  '90-day minimum',
  'Renta mínima flexible de 90 días',
  'Flexible 90-day minimum rental',
  'https://velgoadpmhssqptkcjam.supabase.co/storage/v1/object/public/project-images/projects/bloom-building.webp',
  'projects/bloom-building.webp',
  500000,
  20,
  true,
  false
)
on conflict do nothing;
