delete from public.projects
where title in ('FLOW HOUSE', 'MANDARIN ORIENTAL RESIDENCES');

insert into public.projects (
  title,
  badge_es,
  badge_en,
  location_es,
  location_en,
  residences_es,
  residences_en,
  baths_es,
  baths_en,
  type_es,
  type_en,
  delivery_es,
  delivery_en,
  ideal_for_es,
  ideal_for_en,
  parking_es,
  parking_en,
  hook_es,
  hook_en,
  filter_location_es,
  filter_location_en,
  filter_type_es,
  filter_type_en,
  filter_strategy_es,
  filter_strategy_en,
  image_url,
  image_path,
  price_from,
  sort_order,
  is_published,
  is_featured
)
values (
  'MANDARIN ORIENTAL RESIDENCES',
  'Ultra lujo waterfront',
  'Ultra-luxury waterfront',
  'Brickell Key, Miami',
  'Brickell Key, Miami',
  'Residencias de 2, 3, 4 & 5 habitaciones',
  '2, 3, 4 & 5 bedroom residences',
  '—',
  '—',
  'Restricciones de renta',
  'Rental restrictions',
  '2030',
  '2030',
  'Compradores de alto patrimonio que buscan preservar capital en una propiedad icónica, con servicio cinco estrellas y ubicación irrepetible en Miami.',
  'High-net-worth buyers seeking to preserve capital in an iconic property with five-star service and an irreplaceable Miami location.',
  null,
  null,
  'Ultra lujo frente al agua en Brickell Key con el legendario servicio de Mandarin Oriental.',
  'Waterfront ultra-luxury on Brickell Key with the legendary Mandarin Oriental service.',
  'Brickell Key, Miami',
  'Brickell Key, Miami',
  'Restricciones de renta',
  'Rental restrictions',
  'Preservación de capital en propiedad icónica frente al agua',
  'Capital preservation in an iconic waterfront property',
  'https://velgoadpmhssqptkcjam.supabase.co/storage/v1/object/public/project-images/projects/mandarin-oriental-residences/hero.webp',
  'projects/mandarin-oriental-residences/hero.webp',
  6000000,
  40,
  true,
  false
);
